// Accumulated travel preferences for a session, stored in DB
export interface TravelPreferences {
  budget: number | null;
  currency: string;
  origin: string | null;
  destination: string | null;
  tripLengthDays: number | null;
  interests: string[];
  hotelMinStars: number | null;
  hotelMaxStars: number | null;
  maxLayovers: number | null;
  departureDate: string | null;  // ISO "YYYY-MM-DD"
  returnDate: string | null;     // ISO "YYYY-MM-DD"
  isComplete: boolean;
}

// Returns a blank preferences object with safe defaults
export function emptyPreferences(): TravelPreferences {
  return {
    budget: null,
    currency: "USD",
    origin: null,
    destination: null,
    tripLengthDays: null,
    interests: [],
    hotelMinStars: null,
    hotelMaxStars: null,
    maxLayovers: null,
    departureDate: null,
    returnDate: null,
    isComplete: false,
  };
}

// The 4 fields that must all be non-null before itinerary generation runs
export const REQUIRED_PREFERENCE_FIELDS = [
  "budget",
  "origin",
  "destination",
  "tripLengthDays",
] as const;

// Partial update applied to a session's preferences (only provided fields are changed)
export interface PreferencesUpdate {
  budget?: number;
  currency?: string;
  origin?: string;
  destination?: string;
  tripLengthDays?: number;
  interests?: string[];
  hotelMinStars?: number;
  hotelMaxStars?: number;
  maxLayovers?: number;
  departureDate?: string;
  returnDate?: string;
}

// The JSON shape Ollama must return for every message
export interface ClaudeStructuredResponse {
  message: string;
  preferencesUpdate: PreferencesUpdate | null;
  isComplete: boolean;
  missingFields: string[];
  itineraries: GeneratedItinerary[] | null;  // unused by server; kept for prompt fidelity
}

// An itinerary as generated by generateItinerariesFromData (no DB id yet)
export interface GeneratedItinerary {
  destination: string;
  countryFlag: string;
  nights: number;
  totalCost: number;
  flight: {
    airline: string;
    origin: string;
    destination: string;
    price: number;
  };
  hotel: {
    name: string;
    stars: number;
    pricePerNight: number;
  };
  dailyBudget: number;
}
